[Variables]
; -------------------------------------------------------------------------------
; VariablesDefault.inc should contain all or most of the variables required for the app's function, especially user settings.
; VariablesDefault.inc keys and values are the default settings when the app is first installed or reinstalled.
; Any settings changed by the user should be written to Variables.inc, not VariablesDefault.inc.
; All keys in Variables.inc supercede the identical keys of VariablesDefault.inc. 
; VariablesDefault.inc acts as a backup and fallback.
; -------------------------------------------------------------------------------

; -------------------------------------------------------------------------------
; Below variables are required for the app's function. Do not remove or change.
; -------------------------------------------------------------------------------

MyAppID=ToolTipster-TheyCallMePapa
MyAppName=ToolTipster
MyAppAuthor=TheyCallMePapa
MyVariablesLoc=#SKINSPATH#Droptop Community Apps\Apps\ToolTipster-TheyCallMePapa\Variables\Variables.inc
MyAppGUID=

; -------------------------------------------------------------------------------
; Add your variables below: 
; -------------------------------------------------------------------------------
Actiontip=1
Alarmtip=1
Appdrawertip=1
Assistanttip=1
Batterytip=1
Copytip=1
Downloads=1
Language=1
Mailtip=1
MONDtip=1
Desktoptip=1
Recenttip=1
Searchtip=1
Timetip=1
Volumetip=1
Weathertip=1
Wifitip=1